\" Written and placed in the public domain by Brian de Alwis
.Dd 2009/01/09
.Dt pbfile 1
.Os Darwin
.Sh NAME
.Nm pbfile
.Nd copy file references to the clipboard
.Sh SYNOPSIS
.Nm
file ...
.Sh DESCRIPTION
.Nm
copies references for the provided files to the clipboard.
Mail.app, for example, will treat the files as attachments
when pasted into a message.
.Sh SEE ALSO 
.Xr pbcopy 1 ,
.Xr pbpaste 1
